sulu_tag_api:
    resource: "../../vendor/sulu/sulu/src/Sulu/Bundle/TagBundle/Resources/config/routing_api.yaml"
    prefix:   /admin/api

sulu_admin:
    resource: "../../vendor/sulu/sulu/src/Sulu/Bundle/AdminBundle/Resources/config/routing.yaml"
    prefix: /admin

sulu_admin_api:
    resource: "../../vendor/sulu/sulu/src/Sulu/Bundle/AdminBundle/Resources/config/routing_api.yaml"
    prefix: /admin/api

sulu_contact_api:
    resource: "../../vendor/sulu/sulu/src/Sulu/Bundle/ContactBundle/Resources/config/routing_api.yaml"
    prefix: /admin/api

sulu_security:
    resource: "../../vendor/sulu/sulu/src/Sulu/Bundle/SecurityBundle/Resources/config/routing.yaml"
    prefix: /admin/security

sulu_security_api:
    resource: "../../vendor/sulu/sulu/src/Sulu/Bundle/SecurityBundle/Resources/config/routing_api.yaml"
    prefix: /admin/api

sulu_page_api:
    resource: "../../vendor/sulu/sulu/packages/page/config/routing_admin_api.yaml"
    prefix: /admin/api

sulu_media:
    resource: "../../vendor/sulu/sulu/src/Sulu/Bundle/MediaBundle/Resources/config/routing.yaml"
    prefix: /admin/media

sulu_media_website:
    resource: "../../vendor/sulu/sulu/src/Sulu/Bundle/MediaBundle/Resources/config/routing_website.yaml"

sulu_media_api:
    resource: "../../vendor/sulu/sulu/src/Sulu/Bundle/MediaBundle/Resources/config/routing_api.yaml"
    prefix: /admin/api

sulu_category_api:
    resource: "../../vendor/sulu/sulu/src/Sulu/Bundle/CategoryBundle/Resources/config/routing_api.yaml"
    prefix: /admin/api

sulu_snippet_api:
    resource: "../../vendor/sulu/sulu/packages/snippet/config/routing_admin_api.yaml"
    prefix: /admin/api

sulu_location:
    resource: "../../vendor/sulu/sulu/src/Sulu/Bundle/LocationBundle/Resources/config/routing.yaml"
    prefix: /admin/location

sulu_website:
    resource: "../../vendor/sulu/sulu/src/Sulu/Bundle/WebsiteBundle/Resources/config/routing.yaml"
    prefix: /admin/website

sulu_website_api:
    resource: "../../vendor/sulu/sulu/src/Sulu/Bundle/WebsiteBundle/Resources/config/routing_api.yaml"
    prefix: /admin/api

sulu_core:
    resource: "../../vendor/sulu/sulu/src/Sulu/Bundle/CoreBundle/Resources/config/routing_api.yaml"
    prefix: /admin/api

sulu_custom_urls_api:
    resource: "../../vendor/sulu/sulu/packages/custom-url/config/routing_admin_api.yaml"
    prefix: /admin/api

sulu_route_api:
    resource: "../../vendor/sulu/sulu/packages/route/config/routing_admin_api.yaml"
    prefix: /admin/api

sulu_preview:
    resource: "../../vendor/sulu/sulu/src/Sulu/Bundle/PreviewBundle/Resources/config/routing.yaml"
    prefix: /admin/preview

sulu_preview_api:
    resource: "../../vendor/sulu/sulu/src/Sulu/Bundle/PreviewBundle/Resources/config/routing_api.yaml"
    prefix: /admin/api

sulu_preview_public:
    resource: "../../vendor/sulu/sulu/src/Sulu/Bundle/PreviewBundle/Resources/config/routing_public.yaml"
    prefix: /admin/p

sulu_search:
    resource: "../../vendor/sulu/sulu/packages/search/config/routing_admin_api.yaml"
    prefix: /admin/search

sulu_activity_api:
    resource: "../../vendor/sulu/sulu/src/Sulu/Bundle/ActivityBundle/Resources/config/routing_api.yaml"
    prefix: /admin/api

sulu_trash_api:
    resource: "../../vendor/sulu/sulu/src/Sulu/Bundle/TrashBundle/Resources/config/routing_api.yaml"
    prefix: /admin/api

sulu_reference_api:
    resource: "../../vendor/sulu/sulu/src/Sulu/Bundle/ReferenceBundle/Resources/config/routing_api.yaml"
    prefix: /admin/api
